defaults:
  - hparams: default
  - datamodule: default
  - model: ???
  - trainer: default
  - trainer/logger: wandb
  - trainer/callbacks: default
  - _self_

data_base_path: /home/kneidell/data
logs_base_path: /home/kneidell/Documents/logs
